# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: speechify.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'speechify.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fspeechify.proto\x12\tspeechify\"/\n\x0cLoginRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"%\n\rTokenResponse\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\"J\n\x15\x43reateDocumentRequest\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0c\n\x04text\x18\x03 \x01(\t\"K\n\x0e\x44ocumentDetail\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08owner_id\x18\x02 \x01(\x05\x12\r\n\x05title\x18\x03 \x01(\t\x12\x0c\n\x04text\x18\x04 \x01(\t\",\n\x14ListDocumentsRequest\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\"O\n\x0f\x44ocumentSummary\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\x11\n\taudio_url\x18\x04 \x01(\t\"F\n\x15ListDocumentsResponse\x12-\n\tdocuments\x18\x01 \x03(\x0b\x32\x1a.speechify.DocumentSummary\"?\n\x12GetDocumentRequest\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\x12\x13\n\x0b\x64ocument_id\x18\x02 \x01(\x05\x32\xba\x02\n\x10SpeechifyService\x12:\n\x05Login\x12\x17.speechify.LoginRequest\x1a\x18.speechify.TokenResponse\x12M\n\x0e\x43reateDocument\x12 .speechify.CreateDocumentRequest\x1a\x19.speechify.DocumentDetail\x12R\n\rListDocuments\x12\x1f.speechify.ListDocumentsRequest\x1a .speechify.ListDocumentsResponse\x12G\n\x0bGetDocument\x12\x1d.speechify.GetDocumentRequest\x1a\x19.speechify.DocumentDetailb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'speechify_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGINREQUEST']._serialized_start=30
  _globals['_LOGINREQUEST']._serialized_end=77
  _globals['_TOKENRESPONSE']._serialized_start=79
  _globals['_TOKENRESPONSE']._serialized_end=116
  _globals['_CREATEDOCUMENTREQUEST']._serialized_start=118
  _globals['_CREATEDOCUMENTREQUEST']._serialized_end=192
  _globals['_DOCUMENTDETAIL']._serialized_start=194
  _globals['_DOCUMENTDETAIL']._serialized_end=269
  _globals['_LISTDOCUMENTSREQUEST']._serialized_start=271
  _globals['_LISTDOCUMENTSREQUEST']._serialized_end=315
  _globals['_DOCUMENTSUMMARY']._serialized_start=317
  _globals['_DOCUMENTSUMMARY']._serialized_end=396
  _globals['_LISTDOCUMENTSRESPONSE']._serialized_start=398
  _globals['_LISTDOCUMENTSRESPONSE']._serialized_end=468
  _globals['_GETDOCUMENTREQUEST']._serialized_start=470
  _globals['_GETDOCUMENTREQUEST']._serialized_end=533
  _globals['_SPEECHIFYSERVICE']._serialized_start=536
  _globals['_SPEECHIFYSERVICE']._serialized_end=850
# @@protoc_insertion_point(module_scope)
